services:
  - type: web
    name: crpms-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DB_HOST
        generateValue: true
      - key: DB_USER
        generateValue: true
      - key: DB_PASSWORD
        generateValue: true
      - key: DB_NAME
        value: CRPMS
      - key: JWT_SECRET
        generateValue: true
