-- CRPMS Database Setup
CREATE DATABASE IF NOT EXISTS CRPMS;
USE CRPMS;

CREATE TABLE IF NOT EXISTS User (
  userId INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Services (
  serviceCode INT PRIMARY KEY AUTO_INCREMENT,
  serviceName VARCHAR(100) NOT NULL,
  servicePrice DECIMAL(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS Car (
  plateNumber VARCHAR(20) PRIMARY KEY,
  type VARCHAR(50) NOT NULL,
  model VARCHAR(50) NOT NULL,
  manufacturingYear INT NOT NULL,
  driverPhone VARCHAR(20) NOT NULL,
  mechanicName VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ServiceRecord (
  recordNumber INT PRIMARY KEY AUTO_INCREMENT,
  serviceDate DATE NOT NULL,
  plateNumber VARCHAR(20) NOT NULL,
  serviceCode INT NOT NULL,
  FOREIGN KEY (plateNumber) REFERENCES Car(plateNumber) ON DELETE CASCADE,
  FOREIGN KEY (serviceCode) REFERENCES Services(serviceCode) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Payment (
  paymentNumber INT PRIMARY KEY AUTO_INCREMENT,
  amountPaid DECIMAL(10,2) NOT NULL,
  paymentDate DATE NOT NULL,
  recordNumber INT NOT NULL,
  receivedBy INT,
  FOREIGN KEY (recordNumber) REFERENCES ServiceRecord(recordNumber) ON DELETE CASCADE,
  FOREIGN KEY (receivedBy) REFERENCES User(userId)
);
